name: Main CI
on:
  push:
    branches:
      - '*'
    tags-ignore:
      - '*'
  pull_request:
    branches:
      - '*'

jobs:
  lint:
    name: Run Lint Check
    uses: ./.github/workflows/lint.yml

  check:
    needs: lint
    name: Run checks
    uses: ./.github/workflows/check.yml
